"""Synthetic metadata only. No media is decoded or generated by these fixtures."""
from copy import deepcopy
import hashlib
import json

HASH = {"algorithm": "sha256", "hex": "ab" * 32}


def json_digest(value):
    text = json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return {"algorithm": "sha256", "hex": hashlib.sha256(text.encode("utf-8")).hexdigest()}


def header(name, id):
    return {"kind": "kmin." + name, "schema_version": "2.0.0", "id": id,
            "extensions": {}, "required_features": []}


def settings():
    return {"prompt": "A cinematic scene. / Сцена", "prompt_recipe_id": None,
            "seed": "18446744073709551615", "control_spec_id": "ctrl-canny",
            "audio_mode": "preserve", "reference_binding_ids": [],
            "continuity_policy": "none", "spatial_policy": "preserve_display_pad",
            "render_profile_id": "profile-source-only"}


def media(id="media-cfr", role="prepared_video"):
    return {"id": id, "role": role,
            "locator": {"scheme": "project_relative", "path": "media/Сцена 1/clip.bin"},
            "fingerprint": {"digest": deepcopy(HASH), "byte_size": 0, "mtime_ns": "0",
                            "video_stream": 0, "audio_stream": None,
                            "probe_version": "synthetic/1", "decoder_version": "not-run"},
            "probe": {"video": {"codec": "synthetic", "stream_index": 0,
                                  "time_base": {"num": 1, "den": 24},
                                  "first_pts": 0, "end_pts": 360,
                                  "pts_digest": deepcopy(HASH),
                                  "rate": {"num": 24, "den": 1}, "vfr": False,
                                  "width": 640, "height": 360, "rotation": 0,
                                  "sar": {"num": 1, "den": 1}, "display_matrix": [],
                                  "color": "bt709", "pixel_format": "rgb24"},
                      "audio": None},
            "availability": "missing",
            "error": {"code": "SOURCE_MISSING", "message": "Synthetic fixture; no asset supplied.",
                      "stage": "validate", "retryable": False, "details": {}}}


def control():
    return {**header("control_spec", "ctrl-canny"), "type": "canny", "enabled": True,
            "backend": {"id": "comfy-native-canny", "version": "source-b87fe48",
                        "parameters": {"low_threshold": 0.4, "high_threshold": 0.8},
                        "model_digest": None, "temporal_policy": "fixed_parameters"},
            "strength": 1.0, "schedule": {"start_percent": 0.0, "end_percent": 1.0},
            "conditioning_role": "structural_control_video",
            "compatibility": {"profile_ids": ["profile-source-only"], "evidence": "source_only"},
            "preprocess_version": "canny/1", "map_fingerprint": None}


def profile():
    return {"id": "profile-source-only", "version": "native-h3/1",
            "evidence": "source_only", "receipts": [], "fps": {"num": 24, "den": 1},
            "lattice": {"offset": 5, "step": 17}, "shape_min": 5,
            "policy_inference_min": 124, "policy_inference_max": 345,
            "policy_duration_max": {"num": 15, "den": 1}, "grid": 32,
            "base_family": "ref2va", "components": {}, "node_signatures": {},
            "core_revision": "b87fe48b0491425f682f7ffdaed56d0387cb6c5d",
            "runtime": {}, "sampling": {}, "control_branch": {}, "memory_policy": "one_window"}


def spatial():
    return {"id": "space-1", "version": "spatial/1", "coded_width": 640, "coded_height": 360,
            "source_sar": {"num": 1, "den": 1}, "display_matrix": [],
            "display_width": 640, "display_height": 360, "scale": {"num": 1, "den": 1},
            "fitted_width": 640, "fitted_height": 360, "canvas_width": 640, "canvas_height": 384,
            "content_rect": {"x": 0, "y": 12, "width": 640, "height": 360},
            "pad_fill": {"rgb": [0, 0, 0], "control": [0, 0, 0], "mask": 0},
            "resampler": "none", "color_conversion": "rgb24", "output_width": 640,
            "output_height": 360, "output_sar": {"num": 1, "den": 1}}


def segment():
    return {**header("segment", "seg-1"), "revision": 1, "project_id": "proj-1",
            "useful_range": {"start": 0, "end": 360}, "source_range": {"start": 0, "end": 360},
            "source_media_id": "media-cfr", "boundary_before": "first", "continuity_group_id": "shot-1",
            "overrides": {}, "analysis_ids": [], "prompt_draft_ids": [],
            "selected": True, "passthrough": False}


def window():
    return {**header("generation_window", "win-1"), "project_id": "proj-1", "segment_id": "seg-1",
            "plan_revision": 1, "ordinal": 0, "useful_range": {"start": 0, "end": 180},
            "inference_frame_count": 192, "output_useful_range": {"start": 0, "end": 180},
            "input_spans": [
                {"role": "useful", "inference_range": {"start": 0, "end": 180},
                 "media_id": "media-cfr", "source_range": {"start": 0, "end": 180}},
                {"role": "padding", "inference_range": {"start": 180, "end": 192}, "repeat_frame": 179}],
            "context": {"mode": "none", "before": 0, "after": 0,
                        "dependency_result_ids": [], "continuation_state_id": None},
            "padding": {"before": 0, "after": 12, "method": "repeat_boundary"},
            "spatial_transform_id": "space-1", "control_spec_id": "ctrl-canny",
            "render_profile_id": "profile-source-only", "resolved_settings": settings(),
            "resolved_settings_digest": json_digest(settings()), "plan_digest": deepcopy(HASH),
            "generation_key": deepcopy(HASH), "compiled_prompt": "A cinematic scene.",
            "prompt_recipe_id": None, "reference_manifest": []}


def audio():
    return {"mode": "preserve", "source_media_id": None, "source_offset": {"num": 0, "den": 1},
            "sample_rate": 48000, "channel_layout": "stereo", "decisions": [],
            "rounding": "absolute_half_up", "sample_count": 720000, "codec": {}, "presentation": {}}


def project():
    return {**header("project", "proj-1"), "revision": 1, "fps": {"num": 24, "den": 1},
            "frame_count": 360, "source_media_id": "media-source", "canonical_media_id": "media-cfr",
            "normalization": {"version": "cfr24/1", "t0": {"num": 0, "den": 1},
                              "duration": {"num": 15, "den": 1}, "rounded_frame_count": 360,
                              "frame_count": 360, "duration_error": {"num": 0, "den": 1},
                              "duration_clamp": {"applied": False, "reason": None,
                                                 "before_frame_count": 360, "after_frame_count": 360},
                              "pts_digest": deepcopy(HASH), "report": {"evidence": "synthetic_metadata"}},
            "media": {"media-source": media("media-source", "source_video"), "media-cfr": media()},
            "defaults": settings(), "controls": {"ctrl-canny": control()},
            "render_profiles": {"profile-source-only": profile()}, "segments": [segment()],
            "audio_timeline": audio(), "results": {}, "active_result_by_window": {},
            "mode_drafts": {"vid2va": {}, "ref2va": {"saved_note": "Later / Позже"}},
            "detection_proposals": {}, "scene_analyses": {}, "prompt_recipes": {},
            "subjects": {}, "reference_bindings": {}, "continuation_states": {},
            "windows": {}, "spatial_transforms": {"space-1": spatial()}}


def result():
    return {**header("render_result", "result-1"), "request_id": "request-1", "attempt": 1,
            "project_id": "proj-1", "segment_id": "seg-1", "window_id": "win-1",
            "generation_key": deepcopy(HASH), "status": "planned", "stage": "prepare",
            "progress": {"done": 0, "total": 1, "unit": "window"}, "artifacts": [],
            "coverage": None, "audio": None, "provenance": {},
            "validation": {"evidence_kind": "mock", "gpu": "not_performed", "receipts": []},
            "error": None, "warnings": ["Synthetic metadata; no execution."]}


def future_records():
    return {
        "detection_proposal": {**header("detection_proposal", "cut-1"), "project_id": "proj-1",
            "canonical_media_id": "media-cfr", "source_digest": deepcopy(HASH), "boundary_frame": 180,
            "detector": {"id": "synthetic", "version": "1", "parameters": {}}, "score": 0.5,
            "score_scale": "illustration", "evidence_media_ids": [], "state": "proposed",
            "accepted_boundary": None, "decision_revision": 0},
        "scene_analysis": {**header("scene_analysis", "analysis-1"), "project_id": "proj-1",
            "segment_id": "seg-1", "segment_revision": 1, "source_digest": deepcopy(HASH),
            "analyzer": {"id": "not-run", "version": "1", "model_digest": None},
            "sampling_recipe": {}, "chunks": [], "samples": [], "unobserved_intervals": [{"start": 0, "end": 360}],
            "max_sample_gap": 360, "observations": [], "no_inferred_transcript": True,
            "transcript_id": None, "draft_revision": 0, "errors": [], "warnings": ["Not executed."]},
        "prompt_recipe": {**header("prompt_recipe", "recipe-1"), "project_id": "proj-1",
            "segment_id": "seg-1", "revision": 1, "segment_revision": 1, "status": "draft",
            "authored_intent": "Cinematic motion", "dialogue_locks": [], "visible_text_locks": [],
            "analysis_ids": [], "desired_style": "photorealistic", "format_id": "h3.base/1",
            "format_version": "1.0.0", "guide": {"id": "authored", "version": "1"}, "mode": "t2va",
            "blocks": {"integrated_multimodal_description": "A cinematic scene.", "overall_soundscape": "None.",
                       "non_diegetic_music": "None."}, "final_text": "A cinematic scene.",
            "text_digest": {"algorithm": "sha256", "hex": hashlib.sha256(b"A cinematic scene.").hexdigest()},
            "event_ranges": [], "reference_binding_ids": [],
            "validation": {}, "accepted": None, "enhancer": None, "warnings": []},
        "reference_binding": {**header("reference_binding", "binding-1"), "project_id": "proj-1",
            "subject_id": "subject-1", "image_media_id": "image-1", "content_digest": deepcopy(HASH),
            "role": "identity", "segment_ids": ["seg-1"], "useful_ranges": [],
            "appearance_state_id": "appearance-1", "description": "User supplied identity",
            "approved": True, "revision": 1, "retention_instructions": "Keep appearance"},
        "continuation_state": {**header("continuation_state", "state-1"), "project_id": "proj-1",
            "segment_id": "seg-1", "window_id": "win-1", "continuity_group_id": "shot-1",
            "predecessor_result_id": "result-1", "predecessor_digest": deepcopy(HASH),
            "profile_id": "profile-source-only", "component_signatures": {}, "geometry": {},
            "latent_signatures": {}, "artifacts": [], "last_useful_global_end": 180,
            "last_useful_local_end": 180, "video_tail_range": {"start": 158, "end": 180},
            "audio_tail_range": None, "mapping_recipe": "unverified", "overlap_frames": 22,
            "audio_correction": {}, "validity": "unverified", "evidence": "source_only",
            "generation_key": deepcopy(HASH), "revision": 1},
    }
